In [ ]:
import pandas as pd

df = pd.read_csv("diabetes.csv")
df.head()
https://www.kaggle.com/gargmanas/pima-indians-diabetes

In [ ]:
df.isnull().sum()

In [ ]:
df.describe()

In [ ]:
df.Outcome.value_counts()

In [ ]:
X = df.drop("Outcome",axis="columns")
y = df.Outcome

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:3]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, stratify=y, random_state=10)

In [ ]:
X_train.shape

In [ ]:
X_test.shape

In [ ]:
y_train.value_counts()

In [ ]:
201/375

In [ ]:
y_test.value_counts()

In [ ]:
67/125

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

scores = cross_val_score(DecisionTreeClassifier(), X, y, cv=5)
scores

In [ ]:
scores.mean()

In [ ]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
bag_model.fit(X_train, y_train)
bag_model.oob_score_

In [ ]:
bag_model.score(X_test, y_test)

In [ ]:
bag_model = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
scores = cross_val_score(bag_model, X, y, cv=5)
scores

In [ ]:
scores.mean()

In [ ]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(n_estimators=50), X, y, cv=5)
scores.mean()

# Task for Ensemble_Bagging

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("C:/Users/Joshua/Desktop/Machine Learning/heart.csv")
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [4]:
df['ChestPainType'].describe()

count     918
unique      4
top       ASY
freq      496
Name: ChestPainType, dtype: object

In [5]:
df.shape

(918, 12)

In [6]:
# Working to find the outliers.
mean =np.mean(df)
print('mean of the dataset is',mean)

mean of the dataset is Age              53.510893
RestingBP       132.396514
Cholesterol     198.799564
FastingBS         0.233115
MaxHR           136.809368
Oldpeak           0.887364
HeartDisease      0.553377
dtype: float64


In [7]:
std = np.std(df)
print('std deviation is',std)

std deviation is Age               9.427478
RestingBP        18.504067
Cholesterol     109.324551
FastingBS         0.422815
MaxHR            25.446463
Oldpeak           1.065989
HeartDisease      0.497143
dtype: float64


In [8]:
# Now unto finding the Z-score
threshold = 3
outlier = []
for x in df['Age']:
    z = (x - mean)/std
    if z.all() > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

outlier in dataset is []


In [9]:
threshold = 3
outlier = []
for x in df['RestingBP']:
    z = (x - mean)/std
    if z.all() > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

outlier in dataset is []


In [10]:
threshold = 3
outlier = []
for x in df['Cholesterol']:
    z = (x - mean)/std
    if z.all() > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

outlier in dataset is []


In [11]:
threshold = 3
outlier = []
for x in df['FastingBS']:
    z = (x - mean)/std
    if z.all() > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

outlier in dataset is []


In [12]:
threshold = 3
outlier = []
for x in df['MaxHR']:
    z = (x - mean)/std
    if z.all() > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

outlier in dataset is []


In [13]:
threshold = 3
outlier = []
for x in df['Oldpeak']:
    z = (x - mean)/std
    if z.all() > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

outlier in dataset is []


In [14]:
threshold = 3
outlier = []
for x in df['HeartDisease']:
    z = (x - mean)/std
    if z.all() > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

outlier in dataset is []


In [15]:
dummies_0 = pd.get_dummies(df.Sex)
dummies_0.head()

F  M
0  0  1
1  1  0
2  0  1
3  1  0
4  0  1

In [16]:
dummies_1 = pd.get_dummies(df.ChestPainType)
dummies_1.head()

ASY  ATA  NAP  TA
0    0    1    0   0
1    0    0    1   0
2    0    1    0   0
3    1    0    0   0
4    0    0    1   0

In [17]:
dummies_2 = pd.get_dummies(df.RestingECG)
dummies_2.head()

LVH  Normal  ST
0    0       1   0
1    0       1   0
2    0       0   1
3    0       1   0
4    0       1   0

In [18]:
dummies_3 = pd.get_dummies(df.ExerciseAngina)
dummies_3.head()

N  Y
0  1  0
1  1  0
2  1  0
3  0  1
4  1  0

In [19]:
dummies_4 = pd.get_dummies(df.ST_Slope)
dummies_4.head()

Down  Flat  Up
0     0     0   1
1     0     1   0
2     0     0   1
3     0     1   0
4     0     0   1

In [20]:
merged = pd.concat([df,dummies_0,dummies_1,dummies_2,dummies_3,dummies_4],axis='columns')
merged

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak  ... NAP  TA  LVH  Normal  ST  N  Y  Down  \
0      172              N      0.0  ...   0   0    0       1   0  1  0     0   
1      156              N      1.0  ...   1   0    0       1   0  1  0     0   
2       98              N      0.0  ...   0   0    0       0   1  1  0     0   
3      108              Y      1.5  ...   0   0    0       1   0  0  1     0   
4      122              N      0.0  ...   1   0    0       1   0  1  0     0   
..     ...            ...      ...  ...  ..  ..  ...     ...  .. .. ..   ...   
913    132              N      1.2  ...   0   1    0       1   0  1  0     0   
914    141              N      3.4  ...   0   0    0       1   0  1  0     0   
915    115              Y      1.2  ...   0   0    0       1   0  0  1     0   
916    174              N      0.0  ...   0   0    1       0   0  1  0     0   
917    173              N      0.0  ...   1   0    0       1   0  1  0     0   

     Flat  Up  
0       0   1  
1       1   0  
2       0   1  
3       1   0  
4       0   1  
..    ...  ..  
913     1   0  
914     1   0  
915     1   0  
916     1   0  
917     0   1  

[918 rows x 26 columns]

In [21]:
final = merged.drop(['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope','Up'],axis='columns')
final

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  F  \
0     40        140          289          0    172      0.0             0  0   
1     49        160          180          0    156      1.0             1  1   
2     37        130          283          0     98      0.0             0  0   
3     48        138          214          0    108      1.5             1  1   
4     54        150          195          0    122      0.0             0  0   
..   ...        ...          ...        ...    ...      ...           ... ..   
913   45        110          264          0    132      1.2             1  0   
914   68        144          193          1    141      3.4             1  0   
915   57        130          131          0    115      1.2             1  0   
916   57        130          236          0    174      0.0             1  1   
917   38        138          175          0    173      0.0             0  0   

     M  ASY  ATA  NAP  TA  LVH  Normal  ST  N  Y  Down  Flat  
0    1    0    1    0   0    0       1   0  1  0     0     0  
1    0    0    0    1   0    0       1   0  1  0     0     1  
2    1    0    1    0   0    0       0   1  1  0     0     0  
3    0    1    0    0   0    0       1   0  0  1     0     1  
4    1    0    0    1   0    0       1   0  1  0     0     0  
..  ..  ...  ...  ...  ..  ...     ...  .. .. ..   ...   ...  
913  1    0    0    0   1    0       1   0  1  0     0     1  
914  1    1    0    0   0    0       1   0  1  0     0     1  
915  1    1    0    0   0    0       1   0  0  1     0     1  
916  0    0    1    0   0    1       0   0  1  0     0     1  
917  1    0    0    1   0    0       1   0  1  0     0     0  

[918 rows x 20 columns]

In [22]:
X = final.drop(['HeartDisease'],axis='columns')
X

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  F  M  ASY  ATA  \
0     40        140          289          0    172      0.0  0  1    0    1   
1     49        160          180          0    156      1.0  1  0    0    0   
2     37        130          283          0     98      0.0  0  1    0    1   
3     48        138          214          0    108      1.5  1  0    1    0   
4     54        150          195          0    122      0.0  0  1    0    0   
..   ...        ...          ...        ...    ...      ... .. ..  ...  ...   
913   45        110          264          0    132      1.2  0  1    0    0   
914   68        144          193          1    141      3.4  0  1    1    0   
915   57        130          131          0    115      1.2  0  1    1    0   
916   57        130          236          0    174      0.0  1  0    0    1   
917   38        138          175          0    173      0.0  0  1    0    0   

     NAP  TA  LVH  Normal  ST  N  Y  Down  Flat  
0      0   0    0       1   0  1  0     0     0  
1      1   0    0       1   0  1  0     0     1  
2      0   0    0       0   1  1  0     0     0  
3      0   0    0       1   0  0  1     0     1  
4      1   0    0       1   0  1  0     0     0  
..   ...  ..  ...     ...  .. .. ..   ...   ...  
913    0   1    0       1   0  1  0     0     1  
914    0   0    0       1   0  1  0     0     1  
915    0   0    0       1   0  0  1     0     1  
916    0   0    1       0   0  1  0     0     1  
917    1   0    0       1   0  1  0     0     0  

[918 rows x 19 columns]

In [23]:
y = df.HeartDisease
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.4331398 ,  0.41090889,  0.82507026, ..., -0.8235563 ,
        -0.27144836, -1.00218103],
       [-0.47848359,  1.49175234, -0.17196105, ..., -0.8235563 ,
        -0.27144836,  0.99782372],
       [-1.75135854, -0.12951283,  0.7701878 , ..., -0.8235563 ,
        -0.27144836, -1.00218103],
       ...,
       [ 0.37009972, -0.12951283, -0.62016778, ...,  1.21424608,
        -0.27144836,  0.99782372],
       [ 0.37009972, -0.12951283,  0.34027522, ..., -0.8235563 ,
        -0.27144836,  0.99782372],
       [-1.64528563,  0.30282455, -0.21769643, ..., -0.8235563 ,
        -0.27144836, -1.00218103]])

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, stratify=y, random_state=10)

In [27]:
from sklearn.svm import SVC

model = SVC()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8782608695652174

In [28]:
X_train.shape

(688, 19)

In [29]:
X_test.shape

(230, 19)

In [30]:
y_train.value_counts()

1    381
0    307
Name: HeartDisease, dtype: int64

In [31]:
y_test.value_counts()

1    127
0    103
Name: HeartDisease, dtype: int64

In [32]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

scores = cross_val_score(DecisionTreeClassifier(), X, y, cv=5)
scores

array([0.80978261, 0.83695652, 0.77173913, 0.72131148, 0.69398907])

In [33]:
scores.mean()

0.7667557614635305

In [34]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
bag_model.fit(X_train, y_train)
bag_model.oob_score_

0.8502906976744186

In [35]:
bag_model.score(X_test, y_test)

0.8956521739130435

In [36]:
bag_model = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
scores = cross_val_score(bag_model, X, y, cv=5)
scores

array([0.86956522, 0.82608696, 0.82608696, 0.82513661, 0.75409836])

In [37]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(n_estimators=50), X, y, cv=5)
scores.mean()

0.830024946543122