In [32]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits 

In [33]:
digits = load_digits()

In [63]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.3)

In [64]:
model = SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.5314814814814814

In [65]:
from sklearn.model_selection import cross_val_score

In [70]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),digits.data,digits.target,cv=5)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [71]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),digits.data,digits.target,cv=5)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [72]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),digits.data,digits.target,cv=5)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [73]:
from sklearn.model_selection import GridSearchCV

In [75]:
clf = GridSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel' : ['rbf','linear']
},cv=3, return_train_score=False)

clf.fit(digits.data,digits.target)
clf.cv_results_

                  

{'mean_fit_time': array([0.24030217, 0.02517653, 0.23722585, 0.02546962, 0.23143276,
        0.02690371]),
 'std_fit_time': array([0.01434541, 0.00429291, 0.007026  , 0.0037481 , 0.00043914,
        0.00471682]),
 'mean_score_time': array([0.11519925, 0.01562881, 0.1105837 , 0.01142343, 0.11004432,
        0.01008868]),
 'std_score_time': array([3.32423532e-03, 4.30475952e-06, 2.12899678e-04, 9.41903998e-04,
        8.82083107e-04, 6.43288496e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [77]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.240302      0.014345         0.115199        0.003324       1   
1       0.025177      0.004293         0.015629        0.000004       1   
2       0.237226      0.007026         0.110584        0.000213      10   
3       0.025470      0.003748         0.011423        0.000942      10   
4       0.231433      0.000439         0.110044        0.000882      20   
5       0.026904      0.004717         0.010089        0.000006      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.380634   
1       linear   {'C': 1, 'kernel': 'linear'}           0.934891   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.404007   
3       linear  {'C': 10, 'kernel': 'linear'}           0.934891   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.404007   
5       linear  {'C': 20, 'kernel': 'linear'}           0.934891   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0           0.410684           0.512521         0.434613        0.056438   
1           0.958264           0.938230         0.943795        0.010321   
2           0.439065           0.537563         0.460211        0.056537   
3           0.958264           0.938230         0.943795        0.010321   
4           0.439065           0.537563         0.460211        0.056537   
5           0.958264           0.938230         0.943795        0.010321   

   rank_test_score  
0                6  
1                1  
2                4  
3                1  
4                4  
5                1

In [79]:
df[['param_C','param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.434613
1       1       linear         0.943795
2      10          rbf         0.460211
3      10       linear         0.943795
4      20          rbf         0.460211
5      20       linear         0.943795

In [80]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits

In [81]:
clf.best_score_

0.9437952142459656

In [83]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [102]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma='auto'),{
        'C' : [1,10,20],
        'kernel' : ['rbf','linear']
   },
   cv=5,
   return_train_score=False,
   n_iter=2 
)
rs.fit(digits.data,digits.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20       linear         0.947697
1      10       linear         0.947697

In [146]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [158]:
model_params ={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }

   },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators': [1,5,10]
        }
    },
    'LogisticRegression':{
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    },
    'GaussianNB':{
        'model':GaussianNB(),
        'params':{}  
    },
    'MultinomialNB':{
        'model':MultinomialNB(),
        'params':{} 
    },
    'DecisionTree':{
        'model':DecisionTreeClassifier(),
        'params':{
           'criterion':['gini','entropy'] ,
        }    
    }
}

In [159]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
scores = []

for model_name,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=3,return_train_score=False)
    clf.fit(digits.data, digits.target)
    scores.append({
         'model': model_name,
        'best_score': clf.best_score_,
        'best_params':clf.best_params_
    })

In [160]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                   best_params
0                 svm    0.943795  {'C': 1, 'kernel': 'linear'}
1       random_forest    0.902059          {'n_estimators': 10}
2  LogisticRegression    0.919310                      {'C': 1}
3          GaussianNB    0.813578                            {}
4       MultinomialNB    0.870896                            {}
5        DecisionTree    0.783528         {'criterion': 'gini'}