In [12]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.model_selection import train_test_split

In [13]:
from sklearn.datasets import load_iris

In [14]:
flower = load_iris()

In [16]:
X_train, X_test, y_train, y_test = train_test_split(flower.data,flower.target,test_size=0.2)


In [17]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

1.0

In [18]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

1.0

In [19]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

In [20]:
dt = tree.DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.9666666666666667

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
cross_val_score(LogisticRegression(),flower.data, flower.target)

C:\Users\Joshua\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [24]:
cross_val_score(SVC(),flower.data, flower.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [25]:
cross_val_score(RandomForestClassifier(),flower.data, flower.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [26]:
cross_val_score(tree.DecisionTreeClassifier(),flower.data, flower.target)

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])