In [72]:
import pandas as pd
import requests
import io
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [73]:
url = "https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv" 
download = requests.get(url).content

In [74]:
df = pd.read_csv(io.StringIO(download.decode('utf-8')))
df



experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [75]:
df.rename(columns={'test_score(out of 10)':'testscore', 'interview_score(out of 10)':'interviewscore', 'salary($)':'salary'}, inplace=True)

In [76]:
df.columns

Index(['experience', 'testscore', 'interviewscore', 'salary'], dtype='object')

In [77]:
df.head(2)

experience  testscore  interviewscore  salary
0        NaN        8.0               9   50000
1        NaN        8.0               6   45000

In [78]:
import math
median_testscore = math.floor(df.testscore.median())
median_testscore

8

In [79]:
df.testscore =df.testscore.fillna(median_testscore)
df

experience  testscore  interviewscore  salary
0        NaN        8.0               9   50000
1        NaN        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        8.0               7   72000
7     eleven        7.0               8   80000

In [80]:
dataMapping={
              "two": 2,
              "three": 3,
              "five": 5,
              "seven": 7,
              "ten": 10,
              "eleven": 11,
             }

In [81]:
df['experience']= df['experience'].map(dataMapping)
df

experience  testscore  interviewscore  salary
0         NaN        8.0               9   50000
1         NaN        8.0               6   45000
2         5.0        6.0               7   60000
3         2.0       10.0              10   65000
4         7.0        9.0               6   70000
5         3.0        7.0              10   62000
6        10.0        8.0               7   72000
7        11.0        7.0               8   80000

In [82]:
import math
median_experience = math.floor(df.experience.median())
median_experience

6

In [83]:
df.experience =df.experience.fillna(median_experience)
df

experience  testscore  interviewscore  salary
0         6.0        8.0               9   50000
1         6.0        8.0               6   45000
2         5.0        6.0               7   60000
3         2.0       10.0              10   65000
4         7.0        9.0               6   70000
5         3.0        7.0              10   62000
6        10.0        8.0               7   72000
7        11.0        7.0               8   80000

In [84]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','testscore','interviewscore']],df.salary)

LinearRegression()

In [85]:
reg.intercept_

11869.918699186936

In [86]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [87]:
reg.predict([[2,9,6]])

array([47056.91056911])

In [88]:
reg.predict([[12,10,10]])

array([88227.64227642])